# docker-compose.yml
version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password

  web:
    build: .
    command: >
      sh -c "until nc -z db 5432; do sleep 1; done;
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "3000:8000"
    environment:
      DB_HOST: db
      DB_NAME: django_db
      DB_USER: django_user
      DB_PASS: django_password
    depends_on:
      - db

volumes:
  postgres_data: