# Generated by Django 5.1 on 2025-05-17 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='merch',
            name='description',
        ),
        migrations.RemoveField(
            model_name='merch',
            name='type',
        ),
        migrations.RemoveField(
            model_name='merchvariant',
            name='description',
        ),
        migrations.AddField(
            model_name='merchvariant',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchvariant',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchvariant',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='merch',
            field=models.ManyToManyField(related_name='bundles', to='merch.merch'),
        ),
        migrations.AlterField(
            model_name='merchvariant',
            name='merch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='merch.merch'),
        ),
        migrations.AlterField(
            model_name='merchvariant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='merch.merchsize'),
        ),
        migrations.AddField(
            model_name='merchsize',
            name='merch_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='merch.merchtype'),
        ),
        migrations.AddField(
            model_name='merch',
            name='merch_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merches', to='merch.merchtype'),
        ),
    ]
