# Generated by Django 5.1 on 2025-05-17 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_merchsize_merchtype_remove_merch_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='merch_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='merches', to='merch.merchtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merchsize',
            name='merch_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='merch.merchtype'),
            preserve_default=False,
        ),
    ]
