# Generated by Django 5.1 on 2025-05-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_populate_merch_types_and_sizes'),
        ('merch', '0003_alter_merch_merch_type_alter_merchsize_merch_type'),
    ]

    operations = [
    ]
