# Generated by Django 5.1 on 2025-05-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0004_merge_20250517_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='merch',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='merchsize',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='merchtype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='merchvariant',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
