# Generated by Django 5.1 on 2025-05-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proof_of_payment',
            field=models.URLField(blank=True, null=True),
        ),
    ]
